name: Upload docker image

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref }}.${{ github.sha }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Build package
      run: make build
    - name: Publish package
      run: make publish
