name: Upload docker image

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}.${{ github.sha }}
    steps:
    - name: Build package
      run: make build
    - name: Publish package
      run: make publish
